In [ ]:
import torch
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np


In [ ]:
names = open('names.txt','r').read().splitlines()
# names[:10]

In [ ]:
stoi = {name:i+1 for i,name in enumerate(sorted(set(''.join(names))))}
stoi['.'] = 0
itos = {i:name for name,i in stoi.items()}

In [ ]:
xs,ys = [],[]
for name in names[:1]:
  chs = ['.'] + list(name) + ['.']
  for ch1,ch2 in zip(chs[:],chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    xs.append(ix1)
    ys.append(ix2)
xs = torch.tensor(xs,dtype=torch.long)
ys = torch.tensor(ys,dtype=torch.long)
print(xs,ys)

tensor([ 0,  5, 13, 13,  1]) tensor([ 5, 13, 13,  1,  0])


In [ ]:
import torch.nn.functional as F
W = torch.randn((27,27),requires_grad=True)
xenc = F.one_hot(xs,num_classes=27).float()
xenc

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
xenc @ W

tensor([[ 0.2575,  0.0143,  1.2462,  0.6171,  0.8748, -0.7481,  0.6673, -1.1496,
          0.2829,  0.1667,  1.4691, -0.0434,  1.2053, -0.3231, -0.6438, -0.7501,
          0.2295,  1.6048,  0.3042,  0.6965, -2.4163,  0.4364, -0.1225, -0.6765,
          1.9114,  1.2966, -2.4170],
        [-0.8829,  1.1336,  0.5526,  0.8297,  1.7818, -1.5136,  1.1676,  0.1288,
          0.1704,  0.4531,  1.0194, -0.8462, -1.5003, -0.1776, -0.0237, -1.1520,
          0.8112,  0.1076, -1.0327,  2.0496, -0.5161, -0.6632,  0.0919, -0.3787,
          0.6718,  0.2889,  0.6946],
        [ 0.5573, -2.1469,  1.9244, -1.8671, -1.0068,  0.3371, -2.0781, -0.2978,
          0.2574,  0.2479,  1.4764, -0.1432, -0.5857,  0.2714, -0.7313, -0.6572,
         -0.0741, -0.6875,  0.4941, -0.9731,  2.0772,  0.1083, -1.1326,  1.1273,
         -0.2879, -0.2736,  0.3171],
        [ 0.5573, -2.1469,  1.9244, -1.8671, -1.0068,  0.3371, -2.0781, -0.2978,
          0.2574,  0.2479,  1.4764, -0.1432, -0.5857,  0.2714, -0.7313, -0.6572